package com.integration.items;

import com.integration.items.BulkItemFeedRule;
import com.integration.items.InventoryRule;
import com.integration.items.MPItemMatchRule;
import com.integration.items.PriceRule;
import com.integration.items.BulkItemUploadRules;

rule "update BulkItemFeedRule"
	when 
		bulkItemUpload: BulkItemUploadRules()
	then
		
		BulkItemFeedRule itemFeedRule = bulkItemUpload.getBulkItemFeedRule();
		itemFeedRule.setMinSizeToProcess(10);
		
	end

	