package com.integration.items;

import com.integration.items.BulkItemFeedRule;
import com.integration.items.InventoryRule;
import com.integration.items.MPItemMatchRule;
import com.integration.items.PriceRule;
import com.integration.items.BulkItemUploadRules;

rule "update BulkItemFeedRule"
	when 
		bulkItemFeed: com.integration.items.BulkItemUploadRules( )BulkItemFeedRule()
	then
		
	end
rule "update InventoryRule"
	when 
		bulkItemFeed: InventoryRule()
	then
		
	end
rule "update MPItemMatchRule"
	when 
		bulkItemFeed: MPItemMatchRule()
	then
		
	end
rule "update PriceRule"
	when 
		bulkItemFeed: PriceRule()
	then
		
	end	
	