package com.myspace.error_action;

import com.myspace.error_action.ErrorAction;

rule "Return CallCWS"
	when 
		error: ErrorAction(marketplaceCode=="walmart" )
	then
		error.setDiscount(15);
	end
rule "Return SendEmailAndLogError"
	when 
		error: Product(type=="gold")
	then
		error.setDiscount(25);
	end
rule "Return SendEmailAndLogError if MarketPlace not equal to Walmart"
	when 
		error: Product(type=="gold")
	then
		error.setDiscount(25);
	end	