package com.myspace.error_action;

import com.myspace.error_action.ErrorAction;

rule "Return CallCWS"
	when 
		error: ErrorAction((marketplaceCode=="WALMART" || marketplaceCode=="walmart" || marketplaceCode=="Walmart") 
		       && (feedType=="MP_ITEM_MATCH" && errorDetails=="Data_Error"))
	then
		error.setInvokeAction("CallCWS");
	end
rule "Return SendEmailAndLogError if errorDetails not equal to Data_Error"	
	when 
		error: ErrorAction((marketplaceCode=="WALMART" || marketplaceCode=="walmart" || marketplaceCode=="Walmart") 
		       && (feedType=="MP_ITEM_MATCH" && errorDetails!="Data_Error"))
	then
		error.setInvokeAction("SendEmailAndLogError");
	end
rule "Return SendEmailAndLogError if feedType equal to MP_ITEM/PRICE/INVENTORY"	
	when 
		error: ErrorAction((marketplaceCode=="WALMART" || marketplaceCode=="walmart" || marketplaceCode=="Walmart") 
		       && (feedType=="MP_ITEM" || feedType=="PRICE" || feedType=="INVENTORY"))
	then
		error.setInvokeAction("SendEmailAndLogError");
	end	
rule "Return SendEmailAndLogError if MarketPlace not equal to Walmart"
	when 
		error: ErrorAction(marketplaceCode!="WALMART" && marketplaceCode!="walmart" && marketplaceCode!="Walmart")
	then
		error.setInvokeAction("SendEmailAndLogError");
	end	