package com.integration.items;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class bulkItemUploadRule implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public bulkItemUploadRule() {
    }




}