package com.integration.items;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class PriceRule implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int minSizeToProcess;
	private int maxWaitInterval;
	private boolean reprocessFailed;
	private int maxRetries;
	private boolean sendEmailOnMaxRetries;
	private int maxRecordsToSendToMarketplace;

	public PriceRule() {
	}

	public int getMinSizeToProcess() {
		return this.minSizeToProcess;
	}

	public void setMinSizeToProcess(int minSizeToProcess) {
		this.minSizeToProcess = minSizeToProcess;
	}

	public int getMaxWaitInterval() {
		return this.maxWaitInterval;
	}

	public void setMaxWaitInterval(int maxWaitInterval) {
		this.maxWaitInterval = maxWaitInterval;
	}

	public int getMaxRetries() {
		return this.maxRetries;
	}

	public void setMaxRetries(int maxRetries) {
		this.maxRetries = maxRetries;
	}

	public boolean isReprocessFailed() {
		return this.reprocessFailed;
	}

	public void setReprocessFailed(boolean reprocessFailed) {
		this.reprocessFailed = reprocessFailed;
	}

	public boolean isSendEmailOnMaxRetries() {
		return this.sendEmailOnMaxRetries;
	}

	public void setSendEmailOnMaxRetries(boolean sendEmailOnMaxRetries) {
		this.sendEmailOnMaxRetries = sendEmailOnMaxRetries;
	}

	public int getMaxRecordsToSendToMarketplace() {
		return this.maxRecordsToSendToMarketplace;
	}

	public void setMaxRecordsToSendToMarketplace(
			int maxRecordsToSendToMarketplace) {
		this.maxRecordsToSendToMarketplace = maxRecordsToSendToMarketplace;
	}

	public PriceRule(int minSizeToProcess, int maxWaitInterval,
			boolean reprocessFailed, int maxRetries,
			boolean sendEmailOnMaxRetries, int maxRecordsToSendToMarketplace) {
		this.minSizeToProcess = minSizeToProcess;
		this.maxWaitInterval = maxWaitInterval;
		this.reprocessFailed = reprocessFailed;
		this.maxRetries = maxRetries;
		this.sendEmailOnMaxRetries = sendEmailOnMaxRetries;
		this.maxRecordsToSendToMarketplace = maxRecordsToSendToMarketplace;
	}

}