package com.myspace.bulk_item_upload;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InventoryRule implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public InventoryRule() {
    }




}